<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"> <!--html opening tag-->

	<head > <!--HEAD STARTS -->
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="robots" content="all" />
		<meta name="description" content="gios" />
		<meta name="keywords" content="gios" />
		<link rel="shortcut icon" href="#" />
		<!-- <link href="http://www.giosconcept.com/skin/frontend/default/blank/css/reset.css" rel="stylesheet" type="text/css" media="screen" /> -->
		<link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>ThemeTwo/Designer/style.css" type="text/css" media="screen" />
	</head>
	
	
	<body> <!--  body starts -->
	
		<div id="container1"> <!-- container1 starts -->
		
			<div id="div1"><!-- #div2 starts -->
				<h1>mens designer</h1>
				<ul> <!-- unsorted list group 1 -->
					<li><a href="<?php echo $this->getBaseUrl();?>men-s-premium/footwear.html">Footwear</a></li>
					<li><a href="<?php echo $this->getBaseUrl();?>men-s-premium/shirts.html">Shirts</a></li>
					<li><a href="<?php echo $this->getBaseUrl();?>men-s-premium/t-shirts.html">T-Shirts</a></li>
					<li><a href="<?php echo $this->getBaseUrl();?>men-s-premium/hoodies.html">Hoodies</a></li>
					<li><a href="<?php echo $this->getBaseUrl();?>men-s-premium/accessories.html">Accessories</a></li>
					<li><a href="<?php echo $this->getBaseUrl();?>men-s-premium/jackets-coats.html">Jackets &amp; Coats</a></li>
					<li><a href="<?php echo $this->getBaseUrl();?>men-s-premium/jumpers-sweatshirts.html">Jumpers &amp; Sweatshirts</a></li>
					<li><a href="<?php echo $this->getBaseUrl();?>men-s-premium/jeans-trousers.html">Jeans &amp; Trousers</a></li>
					<li><a href="<?php echo $this->getBaseUrl();?>men-s-premium/polo-shirts.html">Polo Shirts</a></li>
					<li><a href="<?php echo $this->getBaseUrl();?>men-s-premium/bags.html">Bags</a></li>
				</ul>
			</div>
			
			<div id="div2"> <!-- #div2 starts -->
				<h1>womens designer</h1>
				<ul><!-- unsorted list group 2 -->
					<li><a href="<?php echo $this->getBaseUrl();?>women-s-premium/footwear.html">Footwear</a></li>
					<li><a href="<?php echo $this->getBaseUrl();?>women-s-premium/tops.html">Tops</a></li>
					<li><a href="<?php echo $this->getBaseUrl();?>women-s-premium/accessories.html">Accessories</a></li>
					<li><a href="<?php echo $this->getBaseUrl();?>women-s-premium/jackets-coats.html">Jackets &amp; Coats</a></li>
					<li><a href="<?php echo $this->getBaseUrl();?>women-s-premium/jumpers-hoodies.html">Jumpers &amp; Hoodies</a></li>
					<li><a href="<?php echo $this->getBaseUrl();?>women-s-premium/jeans-trousers.html">Jeans</a></li>
					<li><a href="<?php echo $this->getBaseUrl();?>women-s-premium/dresses-skirts.html">Dresses &amp; Skirts</a></li>
					<li><a href="<?php echo $this->getBaseUrl();?>women-s-premium/bags-purses.html">Bags &amp; Purses</a></li>
				</ul>
			</div>
			
			<div style="clear:both;"></div> <!-- clear the floats -->
			
		</div> <!-- #container1 ends -->
		
	</body>
	
</html>