<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"> <!--html opening tag-->

	<head> <!--HEAD STARTS -->
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="robots" content="all" />
		<meta name="description" content="gios" />
		<meta name="keywords" content="gios" />
		<link rel="shortcut icon" href="#" />
		<link rel="stylesheet" href="<?php echo $this->getSkinUrl();?>ThemeTwo/history/style1.css" type="text/css" media="screen" />
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.0/jquery.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->getSkinUrl();?>ThemeTwo/history/script1.js"></script>
	</head>
	
	<body> <!--  body starts -->
	
		<div id="container1"> <!-- container1 starts -->
		
			<div id="left_panel"> <!-- #left_panel starts -->
				<div id="left_hor_strip"> <!-- #left_hor_strip begins -->
				</div>
				
				<div id="right_hor_strip">
					<div class="image_box"> <!-- .image_box starts -->
					</div>
					<div class="separator"></div>
					<div class="description_box"> <!-- #description_box begins -->
						<h1>gio's book</h1>
						<p>A brief snapshot to the introduction of Gio's Concept. Please enjoy and share the spirit of GC with your wardrobe this season.

Scroll through the pages using the arrows to the right, then continue shopping!.</p>
					</div>
				</div>
				
				<div style="clear:both"></div> <!-- clear the float -->
				
			</div>
			
		
			<div id="right_panel">	<!-- #right_panel begins -->
				<div id="wrapper_imageBox"> <!-- #wrapper_imageBox starts -->
					
					<div class="image_box"> <!-- .image_box starts -->
						<img src="<?php echo $this->getSkinUrl();?>ThemeTwo/history/images/p1img.jpg" class="show" width="340" height="470" alt=""/>
						<img src="<?php echo $this->getSkinUrl();?>ThemeTwo/history/images/p2img.jpg" width="340" height="470" alt=""/>
						<img src="<?php echo $this->getSkinUrl();?>ThemeTwo/history/images/p3img.jpg" width="340" height="470" alt=""/>
						<img src="<?php echo $this->getSkinUrl();?>ThemeTwo/history/images/p4img.jpg" width="340" height="470" alt=""/>
						<img src="<?php echo $this->getSkinUrl();?>ThemeTwo/history/images/p5img.jpg" width="340" height="470" alt=""/>
						<img src="<?php echo $this->getSkinUrl();?>ThemeTwo/history/images/p6img.jpg" width="340" height="470" alt=""/>
						<img src="<?php echo $this->getSkinUrl();?>ThemeTwo/history/images/p7img.jpg" width="340" height="470" alt=""/>
					</div>
					
				</div>				
				
				<div id="wrapper_descriptionBox"> <!-- #wrapper_descriptionBox starts -->
									
					<div class="description_box"><!-- .description_box begins -->
						
						<div id="div1" class="showtxt"> <!-- PAGE 1 CONTENT BEGINS-->
							<div class="div1">Gio's Concept was crafted out of an era</div>
							<div class="div2">the year was 1986</div>
							<div class="div3">A time when during the week we were all driving around pretending we're in Magnum, P.I.,listening to Bruce Springsteen and coughing up dodgy Crocodile Dundee accents.</div>
						</div>
						
						
						<div id="div2">	<!-- PAGE 2 CONTENT BEGINS-->
							<div class="div1">Gio's Concept was crafted out of an era</div>
							<div class="div2">The weekend being a constant fix of neon glare from down at the disco rocking out to the Pet Shop Boys and telling the girls you’re still waiting to hear about your part in Top Gun II…</div>
						</div>
						
						
						<div id="div3">	<!-- PAGE 3 CONTENT BEGINS-->
							<div class="div1">Gio's Concept was crafted out of an era</div>
							<div class="div2">One late afternoon, like a scene from a Batman movie where Lieutenant Gordon lights up the sky with the Bat-signal - or so they thought - a small group of like minds got together for a chinwag.</div>
						</div>
						
						
						<div id="div4">	<!-- PAGE 4 CONTENT BEGINS-->
							<div class="div1">Gio's Concept was crafted out of an era</div>
							<div class="div2">Having all worked in various sections of the fashion industry, this group, this happy few, this band of brothers, champions of style and vigour, were left asking themselves, ‘what more could they offer..?’ ’ </div>
						</div>
						
						<div id="div5"> <!-- PAGE 5 CONTENT BEGINS-->
							<div class="div1">Gio's Concept was crafted out of an era</div>
							<div class="div2">Several moments later...…</div>
							<div class="div3">...probably after passing conversation over whether MacGyver or Steven Segal had the mullet of choice... for which there is an obvious winner...</div>
						</div>
						
						
						<div id="div6"> <!-- PAGE 6 CONTENT BEGINS-->
							<div class="div1">Gio's Concept was crafted out of an era</div>
							<div class="div2">
								<p>..making sure to give a wider birth than a tamed leopard to Liberace’s wardrobe, it instantly struck that somehow providing an access and insight into the new worlds of hip hop, punk and indie scene’s spreading quickly through the UK might prove an instant hit.</p> 
								
								<p>Combinations of more active-wear delivered through an admiration for, the then,extreme sports: skateboarding, surfing and MC battling meant they could create a new vision for urban Britain.</p> 
							</div>
						</div>
						
						<div id="div7"> <!-- PAGE 7 CONTENT BEGINS-->
							<div class="div1">Gio's Concept was crafted out of an era</div>
							<div class="div2">This (unwittingly) led to creating a concept that would go on to define progressive fashion for over two decades. </div>
						</div>
						
				
					</div>
					
					<div id="arrow_nav_wrapper"> <!-- #arrow_nav_wrapper begins -->
						<div class="leftNav">	<!-- #leftNav begins -->
						</div>
						
						<div class="rightNav">	<!-- #rightNav begins -->
						</div>
					</div>
					
				</div>
				
				
				
				<div style="clear:both"></div> <!-- clear the float -->
			</div>
			
			<div style="clear:both"></div> <!-- clear the float -->
			
		</div>
		
	</body>
	
</html>