<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- mens page -->
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
     <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <title>GIOS CONCEPTS - Mens Page </title>
    <link href="<?php echo $this->getSkinUrl();?>ThemeTwo/men/style/Style.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->getSkinUrl();?>ThemeTwo/men/style/Sprites_Style.css" rel="stylesheet" type="text/css" />
    
    <script src="<?php echo $this->getSkinUrl();?>ThemeTwo/men/js/jquery.js" type="text/javascript"></script>
    <script src="<?php echo $this->getSkinUrl();?>ThemeTwo/men/js/fadeSlideShow.js" type="text/javascript"></script>
    <link href="<?php echo $this->getSkinUrl();?>ThemeTwo/men/style/SlideShow.css" rel="stylesheet" type="text/css" />
	
    <script type="text/javascript">
        jQuery(document).ready(function () {
            jQuery('#slideshow').fadeSlideShow();
        });
</script>

</head>
<body>
<div class="men_">
    <div id="main_container">

            

            <!--SIDE NAVIGATION MENU- -->
        <div id="side_nav">
                <br />
                <div class="underline bold">MEN</div>
                <br />
                <div class="underline bold" style="border-width: 0px; border-style: none">NEW IN </div><br />
                <div class="underline bold" style="border-style: none; color: #000000;" >Browse by Departments</div>
                <ul class="menu">
                        <li><a href="<?php echo $this->getBaseUrl();?>men/shoes.html">Footwear</a></li>
						<li><a href="<?php echo $this->getBaseUrl();?>men/shirts.html">Shirts</a></li>
						<li><a href="<?php echo $this->getBaseUrl();?>men/t-shirts.html">T-Shirts </a></li>
						<li><a href="<?php echo $this->getBaseUrl();?>men/hoodies.html">Hoodies</a></li>
						<li><a href="<?php echo $this->getBaseUrl();?>men/accessories.html">Accessories</a></li>
						<li><a href="<?php echo $this->getBaseUrl();?>men/jackets-coats.html">Jackets &amp; Coats</a></li>
						<li><a href="<?php echo $this->getBaseUrl();?>men/jumpers-sweatshirts.html">Jumpers &amp; Sweatshirts</a></li>
						<li><a href="<?php echo $this->getBaseUrl();?>men/jeans-trousers.html">Jeans &amp; Trousers</a></li>
						<li><a href="<?php echo $this->getBaseUrl();?>men/poloshirts.html">Polo Shirts</a></li>
						<li><a href="<?php echo $this->getBaseUrl();?>men/bag-s.html">Bags</a></li>
						<li><a href="<?php echo $this->getBaseUrl();?>men/shorts-swim.html">Shorts &amp; Swim</a></li>
                </ul>

                <div class="underline bold" style="border-style: none; color: #000000;" >Browse by Collection</div>
                <ul class="menu">
                        <li><a href="<?php echo $this->getBaseUrl();?>a-zbrands">A to Z Brands</a></li>
						<li>Premium Brands</li>
						<li>Streetwear</li>
                </ul>


                <div class="underline bold" style="border-style: none; color: #000000;" >Lifestyle</div>
                <ul class="menu">
                        <li>Gios Blog</li>
						<li>Gios Scouts</li>
						<li>Write for us</li>
						<li>Design for us</li>
                </ul>
        </div>

        <!--SECOND COLOUMN-->

        <div class="column2">
			<a href="<?php echo $this->getBaseUrl();?>men/firetrap.html">
            <img src="<?php echo $this->getSkinUrl();?>ThemeTwo/men/Images/Topleft.jpg" alt="" /><br /></a>
            <br />
            <a href="<?php echo $this->getBaseUrl();?>men/shorts-swim.html">
            <img alt="" src="<?php echo $this->getSkinUrl();?>ThemeTwo/men/Images/Shop-Shorts.jpg" /></a>&nbsp;&nbsp;
            <a href="<?php echo $this->getBaseUrl();?>men/accessories.html">
            <img alt="" src="<?php echo $this->getSkinUrl();?>ThemeTwo/men/Images/Shop-Accessories.jpg" /></a>
            <br />

            
            <div>
                    
                    <a href="<?php echo $this->getBaseUrl();?>a-zbrands">
                    
                    <img src="<?php echo $this->getSkinUrl();?>ThemeTwo/men/Images/130.jpg" alt="" align="right" 
                        style="margin-left: 10px;" /></a>
                   <h6>HEATED FASHION</h6>

                   With a growing number of the biggest and hottest brands of today, we bring your authentic British street fashion from 
                    <strong>Fred Perry;</strong> surf, snow, bike and boardsport inspired clothing from 
                    <strong>Animal;</strong> life energising collections from <strong>Diesel;</strong> iconic collaborations, and one of the largest selections Available Right Here from 
                    <strong>Converse;</strong> truly the sickest headphones from <strong>Skullcandy</strong> and many more! GC bring you 
                    <strong>Unrivalled Style and Selection for Every New Season.<br />
&nbsp;<br />
                    </strong> <span>Hot This Summer!</span>&nbsp; Shop at Gio's Concept 

                   
                   </div>
        </div>


        <!--THIRD COLOUMN-->

        <div class="column3">
                
            <img alt="" src="<?php echo $this->getSkinUrl();?>ThemeTwo/men/Images/img_trans.gif" class="sale" />&nbsp;&nbsp;            
            <img alt="" src="<?php echo $this->getSkinUrl();?>ThemeTwo/men/Images/img_trans.gif" class="blog" />&nbsp;                   
            <a href="<?php echo $this->getBaseUrl();?>mensstyle">
			   <img alt="" src="<?php echo $this->getSkinUrl();?>ThemeTwo/men/Images/img_trans.gif" class="adven" />                    
            </a>            

            <div class="topDot">
                <a href="<?php echo $this->getBaseUrl();?>men/native.html">
               <img src="<?php echo $this->getSkinUrl();?>ThemeTwo/men/Images/editors-choice.jpg" class="picPad" alt="" align="left" /></a><strong>Editor&#8217;s Choice
                <br />
                </strong>Native &#8211; Jefferson | 
                <a href="<?php echo $this->getBaseUrl();?>men/native.html" style="color:#FF0000;">Available Now  </a>
                <br />
                <strong>Inspired by classic, casual silhouettes, but made with the lightest and most comfortable material available, Native shoes are the best of both worlds.</strong>
                <br />

Brought to you all the way from Canada&#8217;s Native, these shoes are a must-have this summer.
                <br />
                <a href="#">Check them out > </a>
            </div> 
           <div class="clear"></div>
            

            <div class="topDot">
                <a href="<?php echo $this->getBaseUrl();?>men/shoes.html">
                <img alt="" src="<?php echo $this->getSkinUrl();?>ThemeTwo/men/Images/ShopFootwear.jpg"/></a>&nbsp;&nbsp;
                <a href="<?php echo $this->getBaseUrl();?>men/t-shirts.html">
                <img alt="" src="<?php echo $this->getSkinUrl();?>ThemeTwo/men/Images/Shop-t-shirts.jpg" /></a>
            </div>

            <div class="topDot">
                
                <div id="slideshowWrapper">
                    <ul id="slideshow">
                        <li>
							<a href="<?php echo $this->getBaseUrl();?>men/giogoi.html">
							<img src="<?php echo $this->getSkinUrl();?>ThemeTwo/men/Images/Scroll-Image-4.jpg" border="0" alt="" />
							</a>
						</li> <!-- This is the last image in the slideshow -->
						<li>
							<a href="<?php echo $this->getBaseUrl();?>men">
							<img src="<?php echo $this->getSkinUrl();?>ThemeTwo/men/Images/Scroll-Image-5.jpg" border="0" alt="" />
							</a>
						</li>
                        <li>
							<a href="<?php echo $this->getBaseUrl();?>men/replay.html">
							<img src="<?php echo $this->getSkinUrl();?>ThemeTwo/men/Images/Scroll-Image-3.jpg" border="0" alt="" />
							</a>
						</li>
                        <li>
							<a href="<?php echo $this->getBaseUrl();?>men/rayban.html">
							<img src="<?php echo $this->getSkinUrl();?>ThemeTwo/men/Images/Scroll-Image-2.jpg" border="0" alt="" />
							</a>
						</li>
                        <li>
							<a href="<?php echo $this->getBaseUrl();?>men/fox.html">
							<img src="<?php echo $this->getSkinUrl();?>ThemeTwo/men/Images/Scroll-Image-1.jpg" border="0" alt="" />
							</a>
						</li> <!-- This is the first image in the slideshow -->
                    </ul><br clear="all" />
                </div>
                          
            </div>

        </div>
        
        <div style="clear:both"></div>  

    </div>

    
</div>
</body>
</html>
