<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- women page - -->
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
     <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <title>GIOS CONCEPTS - Mens Page </title>
    <link href="<?php echo $this->getSkinUrl();?>ThemeTwo/women/style/Style.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->getSkinUrl();?>ThemeTwo/women/style/Sprites_Style.css" rel="stylesheet" type="text/css" />
    
    <script src="<?php echo $this->getSkinUrl();?>ThemeTwo/women/js/jquery.js" type="text/javascript"></script>
    <script src="<?php echo $this->getSkinUrl();?>ThemeTwo/women/js/fadeSlideShow.js" type="text/javascript"></script>
    <link href="<?php echo $this->getSkinUrl();?>ThemeTwo/women/style/SlideShow.css" rel="stylesheet" type="text/css" />

    <script type="text/javascript">
        jQuery(document).ready(function () {
            jQuery('#slideshow').fadeSlideShow();
        });
</script>

</head>
<body>
<div class="women_">
    <div id="main_container">

            

            <!--SIDE NAVIGATION MENU- -->
        <div id="side_nav">
                <br />
                <div class="underline bold">WOMEN</div>
                <br />
                <div class="underline bold" style="border-width: 0px; border-style: none">NEW IN </div><br />
                <div class="underline bold" style="border-style: none; color: #000000;" >Browse by Departments</div>
                <ul class="menu">
                        <li><a href="<?php echo $this->getBaseUrl();?>women/accessories.html">Accessories</a></li>
						<li><a href="<?php echo $this->getBaseUrl();?>women/bags-purses.html">Bags & Purses</a></li>
						<li><a href="<?php echo $this->getBaseUrl();?>women/dresses.html">Dresses</a></li>
						<li><a href="<?php echo $this->getBaseUrl();?>women/shoes.html">Footwear</a></li>
						<li><a href="<?php echo $this->getBaseUrl();?>women/jackets-coats.html">Jackets &amp; Coats</a></li>
						<li><a href="<?php echo $this->getBaseUrl();?>women/jeans.html">Jeans</a></li>
						<li><a href="<?php echo $this->getBaseUrl();?>women/jumpers-hoodies.html">Jumpers &amp; Hoodies</a></li>
						<li><a href="<?php echo $this->getBaseUrl();?>women/shorts-swim.html">Shorts &amp; Swim</a></li>
						<li><a href="<?php echo $this->getBaseUrl();?>women/tops.html">Tops</a></li>
						
                </ul>

                <div class="underline bold" style="border-style: none; color: #000000;" >Browse by Collection</div>
                <ul class="menu">
                        <li><a href="<?php echo $this->getBaseUrl();?>a-zbrandsw">A to Z Brands</a></li>
						<li>Premium Brands</li>
						<li>Streetwear</li>
                </ul>


                <div class="underline bold" style="border-style: none; color: #000000;" >Lifestyle</div>
                <ul class="menu">
                        <li>Gios Blog</li>
						<li>Gios Scouts</li>
						<li>Write for us</li>
						<li>Design for us</li>
                </ul>
        </div>

        <!--SECOND COLOUMN-->

        <div class="column2">
			<a href="<?php echo $this->getBaseUrl();?>women/misssixty.html">
            <img src="<?php echo $this->getSkinUrl();?>ThemeTwo/women/Images/Topleft.jpg" alt="" /><br /></a>
            <br />
            <a href="<?php echo $this->getBaseUrl();?>women/accessories.html">
            <img alt="" src="<?php echo $this->getSkinUrl();?>ThemeTwo/women/Images/Shop-Accessories.jpg" /></a>&nbsp;&nbsp;
            <a href="<?php echo $this->getBaseUrl();?>women/shoes.html">
            <img alt="" src="<?php echo $this->getSkinUrl();?>ThemeTwo/women/Images/Shop-Footwear.jpg" /></a>
            <br />

            
            <div>
                    
                    <a href="<?php echo $this->getBaseUrl();?>a-zbrandsw">
                    
                    <img src="<?php echo $this->getSkinUrl();?>ThemeTwo/women/Images/a-zw.jpg" alt="" align="right" 
                        style="margin-left: 10px;" /></a>
                   <h6>HEATED FASHION</h6>

                   With a growing number of the biggest and hottest brands of today, we bring your authentic British street fashion from 
                    <strong>Fred Perry;</strong> surf, snow, bike and boardsport inspired clothing from 
                    <strong>Animal;</strong> life energising collections from <strong>Diesel;</strong> iconic collaborations, and one of the largest selections Available Right Here from 
                    <strong>Converse;</strong> truly the sickest headphones from <strong>Skullcandy</strong> and many more! GC bring you 
                    <strong>Unrivalled Style and Selection for Every New Season.<br />
&nbsp;<br />
                    </strong> <span>Hot This Summer!</span>&nbsp; Shop at Gio's Concept 

                   
                   </div>
        </div>


        <!--THIRD COLOUMN-->

        <div class="column3">
                
            <img alt="" src="<?php echo $this->getSkinUrl();?>ThemeTwo/women/Images/img_trans.gif" class="sale" />&nbsp;&nbsp;            
            <img alt="" src="<?php echo $this->getSkinUrl();?>ThemeTwo/women/Images/img_trans.gif" class="blog" />&nbsp; 
			<a href="<?php echo $this->getBaseUrl()?>womensstyle">
				<img alt="" src="<?php echo $this->getSkinUrl();?>ThemeTwo/women/Images/img_trans.gif" class="adven" />                    
			</a>
        

          <div class="topDot">
                <a href="<?php echo $this->getBaseUrl();?>fitflop-bronze-pietra.html">
               <img src="<?php echo $this->getSkinUrl();?>ThemeTwo/women/Images/Editors-choice.jpg" class="picPad" alt="" align="left" /></a><strong>Editor&#8217;s Choice
                <br />
                </strong>Fitflop &#8211; Pietra | 
                <a href="<?php echo $this->getBaseUrl();?>women" style="color:#FF0000;">Available Now  </a>
                <br />
                <div>They say it&#8217;s their prettiest sandal yet! The PIETRA is  built on a sleek, minimal metallic microfibre-lined patent upper and  embellished with a strip of three shiny resin stones. Fabulous. Feminine. </div>
                <div> </div>
                <div><strong>It&#8217;s the flip flop with the gym built-in<sup class="sup">TM</sup></strong>.</div>
              <a href="#">Take a peek now > </a>
            </div> 
           <div class="clear"></div>
            

            <div class="topDot">
                <div id="slideshowWrapper">
                    <ul id="slideshow">
                        <li>
							<a href="<?php echo $this->getBaseUrl();?>women/replay.html">
							<img src="<?php echo $this->getSkinUrl();?>ThemeTwo/women/Images/Scroll-Image-5.jpg" border="0" alt="" />
							</a>
						</li> <!-- This is the last image in the slideshow -->

						<li>
							<a href="<?php echo $this->getBaseUrl();?>women/fox.html">
							<img src="<?php echo $this->getSkinUrl();?>ThemeTwo/women/Images/Scroll-Image-4.jpg" border="0" alt="" />
							</a>
						</li> <!-- This is the last image in the slideshow -->
                        <li>
							<a href="<?php echo $this->getBaseUrl();?>women/misssixty.html">
							<img src="<?php echo $this->getSkinUrl();?>ThemeTwo/women/Images/Scroll-Image-3.jpg" border="0" alt="" />
							</a>
						</li>
                        <li>
							<a href="<?php echo $this->getBaseUrl();?>catalogsearch/result/index/?q=rayban&amp;searchgo_x=0&amp;searchgo_y=0">
							<img src="<?php echo $this->getSkinUrl();?>ThemeTwo/women/Images/Scroll-Image-2.jpg" border="0" alt="" />
							</a>
						</li>
                        <li>
							<a href="<?php echo $this->getBaseUrl();?>women/fitflop.html">
							<img src="<?php echo $this->getSkinUrl();?>ThemeTwo/women/Images/Scroll-Image-1.jpg" border="0" alt="" />
							</a>
						</li> <!-- This is the first image in the slideshow -->
                    </ul><br clear="all" />
                </div>
            </div>

            <div class="topDot">
                <a href="<?php echo $this->getBaseUrl();?>women/tops.html">
                <img alt="" src="<?php echo $this->getSkinUrl();?>ThemeTwo/women/Images/Shop-Tops.jpg"/></a>&nbsp;&nbsp;
                <a href="<?php echo $this->getBaseUrl();?>women/dresses.html">
                <img alt="" src="<?php echo $this->getSkinUrl();?>ThemeTwo/women/Images/Shop-Dresses.jpg" /></a>
                          
            </div>

        </div>
        
        <div style="clear:both"></div>  

    </div>

    
<div>
</body>
</html>
