<!-- template file(s) -->
<html>
	<head>
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
		<script src="http://www.maaki.com/thomas/SmoothDivScroll/js/jquery.scrollTo-1.4.0-min.js" type="text/javascript"></script>
		<script src="http://www.maaki.com/thomas/SmoothDivScroll/js/jquery.smoothDivScroll-0.9-min.js" type="text/javascript"></script>
		<script type="text/javascript">
			//<![CDATA[
				 var $h = jQuery.noConflict();
			//]]>
		</script>

		<script type="text/Javascript">
			$h(document).ready(function(){
			$h("img.a").hover(
			function() {
			$h(this).stop().animate({"opacity": "0"}, "slow");
			},
			function() {
			$h(this).stop().animate({"opacity": "1"}, "slow");
			}); 
			 
			});
		</script>
		<script type="text/Javascript">
			$h(document).ready(function() {
				//area 1
				$h('.fade-area-1').children().hover(function() {
					$h(this).siblings().stop().fadeTo(500,0.3);
				}, function() {
					$h(this).siblings().stop().fadeTo(500,1);
				});
				
			});
		</script>

	</head>
	
	<body>
		<!--<img src="{{skin url='../blank/images/media/wallpaper.jpg'}}" alt="Home"/>-->
		<!-- Start of the center content - Fading images -->
		<div id="homePage" class="fade-area-1" id="excepts" style="width:1000px; height:460px; display:block;">
			<div id="women">
				<a href="Women"><img src="<?php echo $this->getSkinUrl();?>images/home/women.jpg" alt="" /></a>
			</div>
			<div id="men">
				<a href="Men"><img src="<?php echo $this->getSkinUrl();?>images/home/mens.jpg" alt="" /></a>
			</div>
			<div id="topItems">
				<a href="men/accessories.html"><img src="<?php echo $this->getSkinUrl();?>images/home/designer.jpg" alt=""  /></a>
			</div>
			<div id="snow">
				<a href="valentines.html?limit=all&cat=360"><img src="<?php echo $this->getSkinUrl();?>images/home/Christmasgifts.jpg" alt="" /></a>
			</div>
		</div>
		<!-- End of the center content -->

		<!-- Start of center text --> 
<div align="center"><font face= 'Palatino Linotype','Book Antiqua',Palatino,serif; font-style: italic><h1>Welcome to GIO'S CONCEPT</font></h1>

<p><div align="LEFT">The Official Site for your fashion fix with exclusive collections for our fashion forward guys and gals. One of the largest ranges of <strong>Converse, Roxy, Quiksilver, DC, Bench, Fred Perry, Animal, Fox, Oakley, O’Neill, Billabong, Weird Fish, Carhartt, Etnies, Globe, Vans, ES, Volcom, Alpinestars, Henleys, Duck and Cover, SC51, Two Stoned, Applebottoms, Miss Sixty, Firetrap, EASTPAK, Timberland, Dirty Dog, FLY53, DVS, Nike, K-Swiss, Gola, Iron Fist, Birkenstock, Desigual, Dr Martens, Diesel, Gio Goi, Lacoste, Havaianas, Paul Frank, Ray-Ban, Fiorelli, Emu, Ugg Australia, Hunter</strong> and many many more!</p>
<p><div align="center"><h2><font face= 'Palatino Linotype','Book Antiqua',Palatino,serif; font-style: italic>Take advantage of our <strong>FREE DELIVERY OFFER*</strong></font></h2></p></div>
<!-- 		<div style="clear:both; height:90px; width:1000px; float:left; background-image:url(http://www.giosconcept.com/skin/frontend/default/blank/images/home/text-block.png);">
			<div style="width:340px; display:inline; padding:10px 10px 0px 10px; float:left; font:12px/1.5 Verdana,Geneva,sans-serif;">
				<strong>
					Featured Collections from Applebottoms, Roxy,
					<br />
					Animal, Havaianas, Quiksilver, Ray-Ban, O'Neill
					<br />
					Firetrap, Hunter Boots, Replay, Dr Martens, FCUK
					<br />
				</strong>
			</div>
			<div style="width:340px; display:inline; padding:10px 10px 0px 10px; float:left; font:12px/1.5 Verdana,Geneva,sans-serif;">
				<strong>
					Latest Men's Trends from brands including
					<br />
					&nbsp;&nbsp;Fly53, Gio Goi, Fred Perry, Henleys, Diesel,
					<br />
					&nbsp;&nbsp;&nbsp;Converse, ES, Globe, Etnies, DC, Vans, Bench
				</strong>
			</div>
			<div style="width:240px; display:inline; padding:10px 10px 10px 20px; float:left; color:white; font-size: 18px; font-family:'Palatino Linotype','Book Antiqua',Palatino,serif; font-style: italic; font-weight:bold;">
				Your online fashion store
				<div style="padding-left: 30px; text-align:right;">
					at GiosConcept.com
				</div>
			</div> -->
		<!-- End of center text -->
	</body>
</html>