<?php
    /**
    * EcommerceTeam.com
    *
    * Seo Layered Navigation
    *
    * @category     Magento Extension
    * @copyright    Copyright (c) 2011 Ecommerce Team (http://www.ecommerce-team.com)
    * @author       Ecommerce Team
    * @version      3.0
    */
    /** @var $this EcommerceTeam_Sln_Block_Layer_Filter_Attribute */

?>
<ol class="sln-type-checkbox">
<?php
    /** @var $_item EcommerceTeam_Sln_Model_Layer_Filter_Item */
    foreach ($this->getAllItems() as $_item):?>
    <li>
        <?php if ($_item->getCount() > 0 && !$_item->getIsSelected()): ?>
            <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>
        <?php elseif($_item->getCount() > 0): ?>
            <a class="checked" href="<?php echo $this->urlEscape($_item->getRemoveUrl()) ?>"><?php echo $_item->getLabel() ?></a>
        <?php else: ?>
            <span class="disabled"><?php echo $_item->getLabel() ?></span>
        <?php endif; ?>
        (<?php echo $_item->getCount() ?>)
    </li>
<?php endforeach ?>
</ol>
